# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d512c3c48151b7c7dd2b4df269bd34310b314f9ac320c596ee5048d647604b9ef4531ebb75535670f09cc2405e48be824267bd10c1d83996cc939c9228d3041f

test:
  secret_key_base: c9a3122e3f4a984ac638d89373eebfe869b103f96ef184372b460d4cf8ef653f87e603da8ef22c69de417cae94a39fc63d228bc567c8e9558322277dc28308ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
